---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: fluentd-system
spec:
  values:
    envFrom:
      - secretRef:
          name: elasticsearch-secrets
      - configMapRef:
          name: elasticsearch-configmap
    extraFilesConfigMapNameOverride: fluentd-config-d-configmap
