---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kafka-operator
  namespace: flux-system
$patch: delete
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: kafka-operator
$patch: delete
