---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello-hpa
  namespace: default
spec:
  chart:
    spec:
      chart: microservice
      # version: "0.1.0"
      version: "0.*"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: titus-charts
        namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
  values:
    fullnameOverride: "hello-hpa"
    image:
      repository: ghcr.io/soft-titus/hello
      tag: 0.0.0 # {"$imagepolicy": "default:hello:tag"}
      fluxImageAutoUpdate:
        enabled: true
        pattern: "^[1-9]+\\.[0-9]+\\.[0-9]+$"
        semver: ">=1.0.0 <2.0.0"
    configMaps:
      env:
        enabled: true
        data:
          LOG_LEVEL: "INFO"
    livenessProbe:
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 75
    service:
      enabled: true
      ports:
        - name: http
          port: 80
          containerPort: 8080
          protocol: TCP
    httpRoute:
      enabled: true
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-gateway-system
      hostnames:
        - hello-hpa.giraffidae.local
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: hello-hpa
              port: 80
    serviceAccount:
      create: false
    podAnnotations:
      reloader.stakater.com/auto: "true"
