---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
$patch: delete
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
$patch: delete
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
$patch: delete
