---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: confluenting
  namespace: flux-system
$patch: delete
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cfk-operator
  namespace: confluent
$patch: delete
