---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
$patch: delete
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
$patch: delete
---
apiVersion: v1
kind: Namespace
metadata:
  name: dragonfly-operator-system
$patch: delete
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: cnpg-system
$patch: delete
