---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
$patch: delete
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
$patch: delete
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
$patch: delete
