---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  values:
    global:
      domain: "argocd.irrawaddy.local"
    configs:
      params:
        server.insecure: true
    server:
      httproute:
        enabled: true
        parentRefs:
          - name: envoy-gateway
            namespace: envoy-gateway-system
        hostnames:
          - "argocd.irrawaddy.local"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  values:
    config:
      log.level: "debug"
      registries:
        - name: GitHub Container Registry
          api_url: https://ghcr.io
          prefix: ghcr.io
          ping: true
          credentials: secret:argocd/ghcr-credential-secrets
