---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: keda
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kedacore
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      # version: "2.18.1"
      version: "2.*"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
  values:
    crds:
      install: true
    watchNamespace: ""
    logging:
      operator:
        level: "info"
      metricServer:
        level: "0"
      webhooks:
        level: "info"
