apiVersion: batch/v1
kind: CronJob
metadata:
  name: kafka-delay-requeue-kafka-heartbeat-cronjob
  namespace: default
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kafka-heartbeat
              image: apache/kafka:4.1.1
              imagePullPolicy: IfNotPresent
              workingDir: /opt/kafka/bin
              envFrom:
                - configMapRef:
                    name: kafka-configmap
                - configMapRef:
                    name: kafka-delay-requeue-env
              command:
                - /bin/bash
                - -ec
                - |
                  echo "Describing topic: ${KAFKA_RETRIABLE_TOPIC}"

                  PARTITION_COUNT=$(./kafka-topics.sh \
                    --bootstrap-server "${KAFKA_BROKER_HOST}:${KAFKA_BROKER_PORT}" \
                    --describe \
                    --topic "${KAFKA_RETRIABLE_TOPIC}" \
                    | sed 's/^[[:space:]]*//' \
                    | grep 'Partition:' \
                    | wc -l)

                  if [ -z "${PARTITION_COUNT}" ]; then
                    echo "Failed to detect partition count"
                    exit 1
                  fi

                  echo "Topic has ${PARTITION_COUNT} partitions"

                  echo "Sending ${PARTITION_COUNT} heartbeat messages (round-robin)"

                  for ((i=0; i<${PARTITION_COUNT}; i++)); do
                    echo "{\"type\":\"heartbeat\",\"source\":\"cronjob\",\"ts\":\"$(date -Iseconds)\"}"
                  done | ./kafka-console-producer.sh \
                    --bootstrap-server "${KAFKA_BROKER_HOST}:${KAFKA_BROKER_PORT}" \
                    --topic "${KAFKA_RETRIABLE_TOPIC}" \
                    --producer-property partitioner.class=org.apache.kafka.clients.producer.RoundRobinPartitioner

                  echo "Kafka heartbeat job completed successfully"
