---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello
  namespace: argocd
spec:
  description: Project for hello apps
  sourceRepos:
    - git@github.com:soft-titus/argocd-apps.git
    - https://soft-titus.github.io/titus-charts
  destinations:
    - namespace: hello*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: autoscaling.k8s.io
      kind: VerticalPodAutoscaler
    - group: argocd-image-updater.argoproj.io
      kind: ImageUpdater
