---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
    namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
#   values:
#     storage:
#       enabled: true
#       requests: 1Gi
#       storageClassName: "default"
