---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    # tag: 1.6.0
    semver: ">= 1.*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
  values:
    deployment:
      replicas: 1
