---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    # tag: 1.6.0
    semver: ">= 1.*"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/dashboard/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://operator.min.io/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator
  ref:
    # tag: 1.3.1
    semver: ">= 1.*"
