---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://mongodb.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-operator
  namespace: mongodb-system
spec:
  chart:
    spec:
      chart: community-operator
      # version: "0.13.0"
      version: "0.*"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
  values:
    operator:
      replicas: 1
      priorityClassName: system-node-critical
      watchNamespace: "*"
