---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      chart: reloader
      # version: "2.2.5"
      version: "2.*"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
