---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fairwinds
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.fairwinds.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: vpa
spec:
  chart:
    spec:
      chart: vpa
      # version: "4.10.1"
      version: "4.*"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
  values:
    fullnameOverride: "vpa"
    priorityClassName: system-node-critical
    admissionController:
      enabled: true
      extraArgs:
        feature-gates: InPlaceOrRecreate=true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 500Mi
    recommender:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          cpu: 200m
          memory: 1000Mi
    updater:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 500Mi
