---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: autoscalers
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: vpa
spec:
  chart:
    spec:
      chart: vertical-pod-autoscaler
      # version: "0.8.0"
      version: "0.*"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: autoscalers
        namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
  values:
    fullnameOverride: "vpa"
    admissionController:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 500Mi
      priorityClassName: system-node-critical
      registerWebhook: false
      certGen:
        enabled: true
    recommender:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          cpu: 200m
          memory: 1000Mi
      priorityClassName: system-node-critical
    updater:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 500Mi
      priorityClassName: system-node-critical
