---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio
spec:
  requestAutoCert: false
  configuration:
    name: storage-configuration
  mountPath: /export
  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 1
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
          storageClassName: default
  users:
    - name: storage-user
  buckets:
    - name: sudoku-images
---
apiVersion: batch/v1
kind: Job
metadata:
  name: set-bucket-policy
  namespace: minio
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-bucket
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for MinIO..."
              until mc alias set minio http://minio.minio.svc.cluster.local $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                sleep 5
              done

              echo "Waiting for bucket sudoku-images..."
              until mc ls minio/sudoku-images >/dev/null 2>&1; do
                sleep 5
              done

              echo "Bucket ready."
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: storage-user
                  key: CONSOLE_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storage-user
                  key: CONSOLE_SECRET_KEY
      containers:
        - name: apply-policy
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Applying policy..."
              mc alias set minio http://minio.minio.svc.cluster.local $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              mc anonymous set download minio/sudoku-images
              echo "Done."
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: storage-user
                  key: CONSOLE_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storage-user
                  key: CONSOLE_SECRET_KEY
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-console
  namespace: minio
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "minio-console.felabella.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: minio-console
          port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio
  namespace: minio
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "minio.felabella.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: minio
          port: 80
