---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-extension
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./env/irrawaddy/core-extension
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: core
