---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-elasticsearch-logs-data-stream-job
  namespace: elastic
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-elasticsearch
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              BASE_URL="${ELASTICSEARCH_SCHEME}://${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}@${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"

              echo "Waiting for Elasticsearch..."
              until curl -s "${BASE_URL}/_cluster/health" | grep -q '"status":"green"'; do
                echo "Not ready, sleeping 5s..."
                sleep 5
              done

              echo "Elasticsearch is Healthy!"
          envFrom:
            - secretRef:
                name: elasticsearch-secrets
            - configMapRef:
                name: elasticsearch-configmap
      containers:
        - name: job
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              BASE_URL="${ELASTICSEARCH_SCHEME}://${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}@${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"

              echo "Checking ILM policy '${ELASTICSEARCH_LOGS_DATA_STREAM_ILM_NAME}'..."
              HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
                "${BASE_URL}/_ilm/policy/${ELASTICSEARCH_LOGS_DATA_STREAM_ILM_NAME}")

              if [ "$HTTP_CODE" = "200" ]; then
                echo "ILM policy already exists."
              else
                echo "Creating ILM policy..."

                curl -s -X PUT "${BASE_URL}/_ilm/policy/${ELASTICSEARCH_LOGS_DATA_STREAM_ILM_NAME}" \
                  -H "Content-Type: application/json" \
                  -d @- <<EOF
              {
                "policy": {
                  "phases": {
                    "hot": {
                      "actions": {
                        "rollover": {
                          "max_primary_shard_size": "1GB",
                          "max_age": "1d"
                        }
                      }
                    },
                    "delete": {
                      "min_age": "7d",
                      "actions": {
                        "delete": {}
                      }
                    }
                  }
                }
              }
              EOF

                echo "ILM policy created."
              fi

              echo "Checking index template '${ELASTICSEARCH_LOGS_DATA_STREAM_INDEX_TEMPLATE_NAME}'..."
              HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
                "${BASE_URL}/_index_template/${ELASTICSEARCH_LOGS_DATA_STREAM_INDEX_TEMPLATE_NAME}")

              if [ "$HTTP_CODE" = "200" ]; then
                echo "Index template already exists."
              else
                echo "Creating index template..."

                curl -s -X PUT "${BASE_URL}/_index_template/${ELASTICSEARCH_LOGS_DATA_STREAM_INDEX_TEMPLATE_NAME}" \
                  -H "Content-Type: application/json" \
                  -d @- <<EOF
              {
                "index_patterns": ["${ELASTICSEARCH_LOGS_DATA_STREAM_NAME}"],
                "data_stream": {},
                "template": {
                  "settings": {
                    "index.lifecycle.name": "${ELASTICSEARCH_LOGS_DATA_STREAM_ILM_NAME}",
                    "index.lifecycle.rollover_alias": "${ELASTICSEARCH_LOGS_DATA_STREAM_NAME}",
                    "number_of_shards": 3,
                    "number_of_replicas": 1
                  },
                  "mappings": {
                    "_data_stream_timestamp": { "enabled": true },
                    "properties": {
                      "@timestamp": { "type": "date" },
                      "host": { "type": "keyword" }
                    }
                  }
                }
              }
              EOF

                echo "Index template created."
              fi

              echo "Checking data stream '${ELASTICSEARCH_LOGS_DATA_STREAM_NAME}'..."
              HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
                "${BASE_URL}/_data_stream/${ELASTICSEARCH_LOGS_DATA_STREAM_NAME}")

              if [ "$HTTP_CODE" = "200" ]; then
                echo "Data stream already exists."
              else
                echo "Creating data stream..."

                curl -s -X PUT "${BASE_URL}/_data_stream/${ELASTICSEARCH_LOGS_DATA_STREAM_NAME}" \
                  -H "Content-Type: application/json" \

                echo "Data stream created."
              fi

          envFrom:
            - secretRef:
                name: elasticsearch-secrets
            - configMapRef:
                name: elasticsearch-configmap
